// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package api_simulator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.ValueNode;
import api_simulator.proxies.ContentAttribute;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_DeserializeJSONstring extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String JsonString;

	public JA_DeserializeJSONstring(
		IContext context,
		java.lang.String _jsonString
	)
	{
		super(context);
		this.JsonString = _jsonString;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		ArrayList<IMendixObject> results = new ArrayList<IMendixObject>();
		ObjectMapper mapper = new ObjectMapper();
		JsonNode root = mapper.readTree(JsonString);

		readJsonObject(	"", root, results);	


		return results;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_DeserializeJSONstring";
	}

	// BEGIN EXTRA CODE
	private void readJsonObject(String currentPath, JsonNode currentNode,ArrayList<IMendixObject> results ) {

		String pathPrefix = currentPath.isEmpty() ? "" : currentPath + ".";

		if (currentNode.isObject()) {
			ObjectNode objectNode = (ObjectNode) currentNode;			
			Iterator<Map.Entry<String, JsonNode>> iter = objectNode.fields();

			while (iter.hasNext()) {
				Map.Entry<String, JsonNode> entry = iter.next();
				readJsonObject(pathPrefix + entry.getKey(), entry.getValue(), results);
        	}
		} else if (currentNode.isArray()) {
			ArrayNode arrayNode = (ArrayNode) currentNode;

			for (int i = 0; i < arrayNode.size(); i++) {				
				readJsonObject(currentPath + "["+i+"]", arrayNode.get(i), results);
			}

		} else if (currentNode.isValueNode()) {
			ValueNode valueNode = (ValueNode) currentNode;
			IMendixObject newContentAttribute = Core.instantiate(getContext(), ContentAttribute.getType());
			newContentAttribute.setValue(getContext(), ContentAttribute.MemberNames.Path.toString(), currentPath);
			newContentAttribute.setValue(getContext(), ContentAttribute.MemberNames.Value.toString(), valueNode.asText());
			results.add(newContentAttribute);			
		}

	}
	// END EXTRA CODE
}
