// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package api_simulator.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import api_simulator.proxies.TemplateVariable;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import java.util.List;
import java.util.ArrayList;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Generates a list of the TemplateVariable entity, the list consists of each (primitive) member as specified in the target entity. The variable code will be returned as {TheAttributeName} (the attribute name, surrounded by curly braces)
 * 
 * This is used during request processing to substitute the template variables using the actual values from the provided input entity
 */
public class JA_GenerateTemplateVariablesForEntity extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String Entity;

	public JA_GenerateTemplateVariablesForEntity(
		IContext context,
		java.lang.String _entity
	)
	{
		super(context);
		this.Entity = _entity;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMetaObject targetEntity = Core.getMetaObject(this.Entity);
		List<IMendixObject> output = new ArrayList<IMendixObject>();
		IContext c = getContext();
		

		for(IMetaPrimitive attrib : targetEntity.getMetaPrimitives() ) {
			TemplateVariable primitiveAttributeVar = TemplateVariable.initialize(c,Core.instantiate(c,TemplateVariable.getType()));
			primitiveAttributeVar.setVariableCode("{"+attrib.getName()+"}");
			output.add(primitiveAttributeVar.getMendixObject());
		}

		return output;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GenerateTemplateVariablesForEntity";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
