// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package api_simulator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.core.Core;
import java.util.Map;
import java.util.LinkedHashMap;

public class JA_RunCustomMicroflow extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String MicroflowName;
	private IMendixObject __Request;
	private api_simulator.proxies.Request Request;

	public JA_RunCustomMicroflow(IContext context, java.lang.String MicroflowName, IMendixObject Request)
	{
		super(context);
		this.MicroflowName = MicroflowName;
		this.__Request = Request;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.Request = this.__Request == null ? null : api_simulator.proxies.Request.initialize(getContext(), __Request);

		// BEGIN USER CODE
		Map<String, Object> params = new LinkedHashMap<String, Object>();				
		params.put("Request", Request.getMendixObject());
		return Core.microflowCall(MicroflowName).withParams(params).execute(getContext());
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_RunCustomMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
