// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package api_simulator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.core.Core;
import java.util.Map;
import java.util.LinkedHashMap;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_RunCustomMicroflow extends UserAction<java.lang.Void>
{
	private final java.lang.String MicroflowName;
	/** @deprecated use Request.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Request;
	private final api_simulator.proxies.Request Request;

	public JA_RunCustomMicroflow(
		IContext context,
		java.lang.String _microflowName,
		IMendixObject _request
	)
	{
		super(context);
		this.MicroflowName = _microflowName;
		this.__Request = _request;
		this.Request = _request == null ? null : api_simulator.proxies.Request.initialize(getContext(), _request);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Map<String, Object> params = new LinkedHashMap<String, Object>();				
		params.put("Request", Request.getMendixObject());
		return Core.microflowCall(MicroflowName).withParams(params).execute(getContext());
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_RunCustomMicroflow";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
