// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package api_simulator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import javax.servlet.http.HttpServletResponse;
import java.io.InputStream;
import java.io.OutputStream;
import com.mendix.m2ee.api.IMxRuntimeResponse;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_WriteBinaryResponse extends UserAction<java.lang.Void>
{
	/** @deprecated use Parameter.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Parameter;
	private final system.proxies.HttpResponse Parameter;
	/** @deprecated use DataFIle.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __DataFIle;
	private final api_simulator.proxies.ResponseDataFile DataFIle;

	public JA_WriteBinaryResponse(
		IContext context,
		IMendixObject _parameter,
		IMendixObject _dataFIle
	)
	{
		super(context);
		this.__Parameter = _parameter;
		this.Parameter = _parameter == null ? null : system.proxies.HttpResponse.initialize(getContext(), _parameter);
		this.__DataFIle = _dataFIle;
		this.DataFIle = _dataFIle == null ? null : api_simulator.proxies.ResponseDataFile.initialize(getContext(), _dataFIle);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext ctx = getContext();
		if (ctx.getRuntimeResponse().isPresent()) {
			IMxRuntimeResponse res = ctx.getRuntimeResponse().get();
			HttpServletResponse servletResponse = res.getHttpServletResponse();
			
			OutputStream targetStream = servletResponse.getOutputStream();
			this.DataFIle.getContents(ctx, targetStream);
		
		}

		return null;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_WriteBinaryResponse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
