// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package api_simulator.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import org.json.XML;
import org.json.JSONObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Converts an XML string to a JSON equivalent. Depends on org.json library
 */
public class JA_XmlToJson extends UserAction<java.lang.String>
{
	private final java.lang.String XmlString;

	public JA_XmlToJson(
		IContext context,
		java.lang.String _xmlString
	)
	{
		super(context);
		this.XmlString = _xmlString;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		final int PRETTY_PRINT_INDENT_FACTOR = 4;

		JSONObject JSONObj = XML.toJSONObject(XmlString);
        String jsonPrettyPrintString = JSONObj.toString(PRETTY_PRINT_INDENT_FACTOR);

		return jsonPrettyPrintString;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_XmlToJson";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
