// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Auto refresh a specific object based on a specified interval (in milliseconds). Output will return the ID that can be passed to the "JSA_StopAutoRefresh" function in case you want to disable auto refresh at a later moment
 * @param {Big} intervalMs - Interval to set the auto refresh to (in milliseconds)
 * @param {MxObject} objectToRefresh
 * @returns {Promise.<Big>}
 */
export async function JSA_StartAutoRefresh(intervalMs, objectToRefresh) {
	// BEGIN USER CODE
	const intervalID = setInterval(function(){
		AutoRefreshObject(objectToRefresh);
	}, intervalMs);

	return intervalID;
	

	function AutoRefreshObject(obj) {
		console.debug("refreshing object..." + obj.getGuid());
		
		if (!obj) {
			console.debug("object not found...");
		}

    	return new Promise(resolve => {
        	mx.data.update({
            	guid: obj.getGuid(),
            	callback: () => resolve(true)
        	});
    	});
	}
	// END USER CODE
}
