// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function findInputField(widgetElement) {
	if (widgetElement) {
		const elements = widgetElement.childNodes;
		var inputTypes = ['text', 'select-one', 'textarea'];
		for (let i = 0; i < elements.length; i++) {
			var elm = elements[i];
			if (typeof elm.type !== 'undefined' && inputTypes.indexOf(elm.type)) {
				return elm;
			}
    	}		
	}

	else {
		return null;
	}
}

// END EXTRA CODE

/**
 * @param {string} targetInputClass
 * @param {Big} targetSelectionStart
 * @param {Big} targetSelectionEnd
 * @returns {Promise.<void>}
 */
export async function JSA_SetCursorPosition(targetInputClass, targetSelectionStart, targetSelectionEnd) {
	// BEGIN USER CODE
	let targetWidget = document.getElementsByClassName(targetInputClass)[0];
	let targetInput = findInputField(targetWidget);

	targetInput.focus();
    targetInput.setSelectionRange(targetSelectionStart, targetSelectionEnd);    

	// END USER CODE
}
