// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function insertAtCursor(myField, myValue) {
    //IE support
    if (document.selection) {
        myField.focus();
        sel = document.selection.createRange();
        sel.text = myValue;
    }
    //MOZILLA and others
    else if (myField.selectionStart || myField.selectionStart == '0') {
        var startPos = myField.selectionStart;
        var endPos = myField.selectionEnd;
        myField.value = myField.value.substring(0, startPos)
            + myValue
            + myField.value.substring(endPos, myField.value.length);
        myField.selectionStart = startPos + myValue.length;
        myField.selectionEnd = startPos + myValue.length;
    } else {
        myField.value += myValue;
    }
}

function findInputField(widgetElement) {
	if (widgetElement) {
		const elements = widgetElement.childNodes;
		var inputTypes = ['text', 'select-one', 'textarea'];
		for (let i = 0; i < elements.length; i++) {
			var elm = elements[i];
			if (typeof elm.type !== 'undefined' && inputTypes.indexOf(elm.type)) {
				return elm;
			}
    	}		
	}

	else {
		return null;
	}
}

// END EXTRA CODE

/**
 * @param {string} targetInputClass
 * @param {string} insertedValue
 * @returns {Promise.<string>}
 */
export async function JSA_ReplaceTextFragmentInlineAtCursor(targetInputClass, insertedValue) {
	// BEGIN USER CODE
	let targetWidget = document.getElementsByClassName(targetInputClass)[0];
	let targetInput = findInputField(targetWidget);

	insertAtCursor(targetInput,insertedValue);

    return targetInput.value;

	// END USER CODE
}
